version: '3.9'
services:
    dankpw:
        image: dankpw
        volumes:
          - /path/to/filedir:/var/www/yaf
          - /path/to/your/yaf.conf:/app/yaf.conf
        ports:
          - '127.0.0.1:4712:4712'

